resolver: lts-13.1
packages:
- '.'
- '../PLPrinter'
- '../PLLabel'
- '../Reversible'
- location:
    git: https://github.com/syallop/DSL-Compose.git
    commit: 5a95ae855f3291aa3193a7424892035226b10d2f
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
