resolver: lts-13.1
packages:
- '.'
- location:
    git: https://github.com/syallop/PLPrinter
    commit: 65f4d3805c06fbbe0e4313f17a2129e5fe2187f9
  extra-dep: true
- location:
    git: https://github.com/syallop/PLLabel
    commit: 9433cf7963e43b4df06f57939218956c3d2dacc4
  extra-dep: true
- location:
    git: https://github.com/syallop/Reversible
    commit: 84188a89af962716dc0534d552da715305cb0cf5
  extra-dep: true
- location:
    git: https://github.com/syallop/DSL-Compose
    commit: 5a95ae855f3291aa3193a7424892035226b10d2f
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
